all:
	gcc start_game.c interface.c enemy.c constants.c mystring.c main_menu.c hero.c read_file.c level.c fight.c character_panel.c items.c inventory.c inventory_panel.c pause_menu.c multiplayer.c server.c -o menu -ansi -pedantic -Wall -Werror -lpthread -lpanel -lncurses
clean:
	rm menu
