all:
	gcc start_game.c interface.c enemy.c constants.c mystring.c main_menu.c hero.c read_file.c level.c fight.c top_panel.c items.c inventory.c -o menu -ansi -pedantic -Wall -Werror -lpanel -lncurses
clean:
	rm menu
